// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamMarket.Infrastructure.Persistence;

#nullable disable

namespace SteamMarket.Infrastructure.Migrations
{
    [DbContext(typeof(SteamMarketDbContext))]
    [Migration("20260707213553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SteamMarket.Infrastructure.Pricing.Models.CachedMarketPrice", b =>
                {
                    b.Property<string>("MarketHashName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MarketHashName");

                    b.ToTable("MarketPrices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
